### ISSUE TITLE
Garland, Grand Prairie, and Dallas South locations not showing up

### ISSUE THREAD

**Issue by stevenmauric** [phamleduy04/texas-dps-scheduler#100]
Hello, 

Thank you for writing this amazing code.

When running script, the locations mentioned do not show. I have tried multiple ZIP codes but only Denton, Plano, and Carrolton show up as nearest locations.

**Comment by phamleduy04** [comment]
Can you try the [official scheduler](https://www.txdpsscheduler.com/) and enter all of the same information to see if all location are showing?

**Comment by stevenmauric** [comment]
Hello,

The official scheduler displays the three locations mentioned above, as closer to my ZIP code than Denton, Plano, and Carrolton.

**Comment by phamleduy04** [comment]
Thanks for replying! Can you test the bot right after the official scheduler at the same time to check if that is an unexpected behaviour?

**Comment by drgrabowski** [comment]
I am having a similar issue, it only shows Denton, Carrollton, Fort Worth, Lake Worth, or Plano. Flower Mound does not show up, but it does give me that option in the scheduler.

**Comment by stevenmauric** [comment]
After testing, I find that the cities do not show up even after submitting on the DPS website at the same time.

**Comment by phamleduy04** [comment]
Thank you, i will take a look of it :)

**Comment by drgrabowski** [comment]
I am using TypeID 71, as of this comment looking at 48 days out until like 280 (for testing since I saw Canyon Falls open up in August). Zip is 76226.

**Comment by stevenmauric** [comment]
Hello again,

After retesting typeID 71 and using the same query 'Apply for First Time DL', the same three locations are showing instead of the closest 5.

**Comment by drgrabowski** [comment]
Tried changing it to typeID 11, I checked the scheduler site again and saw that typeID 71 isn't available, but I still get the same list of locations.

**Comment by phamleduy04** [comment]
> I am using TypeID 71, as of this comment looking at 48 days out until like 280 (for testing since I saw Canyon Falls open up in August). Zip is 76226.

I tried zipcode `76226` with typeID 71 on bot and `Apply for first time DL/permit` on official scheduler this is the output of the bot and official scheduler

<img width="990" alt="Screenshot 2024-02-28 at 2 57 24 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/19d58cff-f113-4b48-8556-154328819746">

<img width="1162" alt="Screenshot 2024-02-28 at 2 57 06 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/e03efdf2-85a9-4bc6-b57f-79ca4e56f173">

**Comment by phamleduy04** [comment]
@stevenmauric can you share your zipcode ?

**Comment by stevenmauric** [comment]
Hi,ZIP 75206On Feb 28, 2024, at 15:01, Duy Pham Le ***@***.***> wrote:﻿
@stevenmauric can you share your zipcode ?

**Comment by drgrabowski** [comment]
I'm starting to see the limitations with the official site now, I can replicate the search on both the script and the official site. It would be nice if we could look at a specific location on a specific date, but I get it if their system doesn't support that.

**Comment by stevenmauric** [comment]
@phamleduy04 75206

**Comment by phamleduy04** [comment]
@stevenmauric, 

I tried 75206 with the "Apply for first time texas DL/Permit" option and typeId 71

<img width="1199" alt="Screenshot 2024-03-04 at 1 41 25 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/3f4cdbc0-4923-44e2-836c-c0fae8fc3ca1">

<img width="979" alt="Screenshot 2024-03-04 at 1 41 50 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/7b56597b-5690-4244-9002-8d0f0423406d">
