### ISSUE TITLE
Repl.it Issue 

### ISSUE THREAD

**Issue by phamleduy04** [phamleduy04/texas-dps-scheduler#101]
I am aware of the repl.it video on the wiki and the steps are no longer working. I will try and update wiki new video to support it :)

**Comment by phamleduy04** [comment]
Updated Github Codespace [wiki](https://github.com/phamleduy04/texas-dps-scheduler/wiki/Installation#github-codespaces)

**Comment by Nicolee0129** [comment]
Hi, I followed all the steps, but at the end it says, 
@Nicolee0129 ➜ /workspaces/texas-dps-scheduler (main) $ npm run start
> texas-dps-scheduler@2.0.0 start
> ts-node --transpile-only src/index.ts
sh: 1: ts-node: not found
How do i fix this?

**Comment by phamleduy04** [comment]
@Nicolee0129 , switch to terminal and try to enter `npm install` then enter. then try the run code button again. If not delete the repl.it and redo it. If not try [Github Codespaces](https://github.com/phamleduy04/texas-dps-scheduler/wiki/Installation#github-codespaces) tutorial ;)

**Comment by Nicolee0129** [comment]
Thank you so much, but unfortunately the dps nearby are all not available
within 30 days lol.

**Comment by phamleduy04** [comment]
you have to keep the bot running since spots will open randomly throughout the day

**Comment by Nicolee0129** [comment]
Ohhh okay~~ thank you so much!

**Comment by srinialtice** [comment]
/usr/bin/env: ‘node’: No such file or directory

**Comment by srinialtice** [comment]
getting the below error, while trying to run it 
/usr/bin/env: ‘node’: No such file or directory

**Comment by phamleduy04** [comment]
I think I got the problem this morning also. Seems like DPS's server has some issue. Try again later I guess.

**Comment by XSERIOX1** [comment]
Is this normal?

[07/30/2024 12:54:17] WARNING -> Got 504 status code
[07/30/2024 12:54:17] ERROR: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>







[07/30/2024 12:54:47] WARNING -> Got 504 status code
[07/30/2024 12:54:47] ERROR: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>







/home/runner/texas-dps-scheduler-1/node_modules/undici/lib/dispatcher/client-h1.js:622
      util.destroy(socket, new HeadersTimeoutError())
                           ^
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as callback] (/home/runner/texas-dps-scheduler-1/node_modules/undici/lib/dispatcher/client-h1.js:622:28)
    at Timeout.onTimeout [as _onTimeout] (/home/runner/texas-dps-scheduler-1/node_modules/undici/lib/util/timers.js:22:13)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}

**Comment by qq295848194** [comment]
I am getting this error in GH codespaces:

WARNING -> Got 403 status code
WARNING -> Got rate limited, sleep for 10s...

Any idea on how to solve?

**Comment by Spikestar05** [comment]
I'm also getting the 
WARNING -> Got 403 status code
WARNING -> Got rate limited, sleep for 10s...

did anyone find a solution?

**Comment by ShubhamM96** [comment]
I'm also getting the
WARNING -> Got 403 status code
WARNING -> Got rate limited, sleep for 10s...

Any info on how to resolve?
