### ISSUE TITLE
Missing TexasScheduler module?

### ISSUE THREAD

**Issue by kuriakoz** [phamleduy04/texas-dps-scheduler#104]
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:1:1 - error TS1434: Unexpected keyword or identifier.

1 require TexasScheduler from './Client';

**Comment by phamleduy04** [comment]
are you using github codespaces?

**Comment by kuriakoz** [comment]
yes I am

**Comment by phamleduy04** [comment]
try to delete the codespace and create a new one

**Comment by kuriakoz** [comment]
its working now with a new codespace and after running "npm install" first thanks

**Comment by phamleduy04** [comment]
no problem glad i can help
