### ISSUE TITLE
Doesn't run due to missing node

### ISSUE THREAD

**Issue by chahatupreti** [phamleduy04/texas-dps-scheduler#105]
Hi,

I was trying to run the code using codespace but got the error - 

`sh: 1: ts-node: not found`

Any suggestions?

**Comment by Shahomie** [comment]
Hi I also got the same issue as well, for context here's the terminal. Thank you.

![Screenshot 2024-02-28 121709](https://github.com/phamleduy04/texas-dps-scheduler/assets/112027838/497b2ef0-dae2-4174-a675-8ac717f1a0d5)

**Comment by phamleduy04** [comment]
can you try `npm install`

**Comment by chahatupreti** [comment]
yes, that worked. Thank you!

**Comment by phamleduy04** [comment]
no problem, i will update the wiki. Sometimes Github codespace doesn't install automatically for you I guess.

**Comment by Shahomie** [comment]
Same here, it's running now. Thanks!
