### ISSUE TITLE
Getting an error: sh: 1: ts-node: not found

### ISSUE THREAD

**Issue by Tyrannax** [phamleduy04/texas-dps-scheduler#106]
When doing the "npm run start" part of the tutorial, it tries starting and then gives me this error:

sh: 1: ts-node: not found

Not sure what that means. Any help would be greatly appreciated!

**Comment by tracer-tick** [comment]
Disclosure: I am not associated with this project. I was simply trying to run it as well and got the same error. 

I was able to fix though by running the following commands:

`npm install tslib`

In my case, I also had to install `tslib`:

`npm install tslib`

Once those two were installed, I could run the program by typing:

`npm run start`

Hope that helps!

**Comment by phamleduy04** [comment]
@tracer-tick , `ts-lib` will be installed when you use `npm install` command. 

https://github.com/phamleduy04/texas-dps-scheduler/blob/main/package.json#L43C1-L43C23

**Comment by tracer-tick** [comment]
Awesome - thank you

**Comment by thisiskabdul** [comment]
If using terminal under VSCode, just do `npm update` to install all the dependency packages for this project.

**Comment by ziserm** [comment]
I also got the error but followed the steps on this forum and it resolved! thanks all

**Comment by DSTEinbach95** [comment]
Was getting the error, then typed npm install tslib   -    after that, works fine.
