### ISSUE TITLE
"AvaLIable" -> "available"

### ISSUE THREAD

**Issue by Erudition** [phamleduy04/texas-dps-scheduler#110]
Thank you for this, amazing solution! Got an appointment tomorrow rather than in 5 months.

Minor issue, but FYI, I noticed that `Available` is misspelled in the interface. When digging into the code to open a PR, I then realized that it's misspelled `avaLIable` everywhere, even in coded module names and such.

**Comment by phamleduy04** [comment]
thanks for pointing that out. It will be fixed on the next release :)
