### ISSUE TITLE
Github Codespace 400 status Error

### ISSUE THREAD

**Issue by Shahomie** [phamleduy04/texas-dps-scheduler#112]
After successfully finding an appointment, the codespace then holds the slot for the appointment. Then it books the appointment, in which after that follows a warning got 400 status code, and an error message saying invalid request. What can be done to solve this issue?

![unnamed](https://github.com/phamleduy04/texas-dps-scheduler/assets/112027838/cdd5c9ef-3b83-485e-aea6-65f8abc07628)

**Comment by Shahomie** [comment]
![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/112027838/2deb7ed7-3db6-4bac-81c3-d54ce8e0867e)

**Comment by phamleduy04** [comment]
I think this has some issues with canceling existing booking feature. You can manually cancel before running the bot

**Comment by phamleduy04** [comment]
Seems like someone already fix this issue with #109
