### ISSUE TITLE
I did the npm install and then run start but then shows this issue

### ISSUE THREAD

**Issue by aaadhairyaaaaa** [phamleduy04/texas-dps-scheduler#115]
![Screenshot 2024-05-30 150023](https://github.com/phamleduy04/texas-dps-scheduler/assets/171287001/14f8839b-50af-4ad2-988c-4987554f7fa4)

**Comment by phamleduy04** [comment]
can you send me the full ZodError?

**Comment by aaadhairyaaaaa** [comment]
sent to your email, ill show here as well
![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/171287001/70fab8b8-ac43-4f0d-847f-94f15bbb8bb9)

**Comment by phamleduy04** [comment]
My guess is you are using the old config file. the zipcode section should be like this (example you are in zipcode 11111)

```
zipCode: ["11111"]
```

If that didn't fix, try to delete the config.yml and rename the `example.config.yml` back to `config.yml` and then fill in the data again
