### ISSUE TITLE
Date and Time not working

### ISSUE THREAD

**Issue by ska6311** [phamleduy04/texas-dps-scheduler#118]
I ran the code and it worked perfectly fine but realized the date was too early, so I cancelled the npm and changed thw date and time and reran it but it did not change and the code ran normally from the old date & time. im not sure if i have the format wrong or what please help
![Capture](https://github.com/phamleduy04/texas-dps-scheduler/assets/171469415/69ed9982-dd40-453b-b074-12c8ffaa7e84)

**Comment by phamleduy04** [comment]
I think you set sameday as true on config.yml
