### ISSUE TITLE
Text Output Change when startDate is set

### ISSUE THREAD

**Issue by gitmatt1000** [phamleduy04/texas-dps-scheduler#119]
In SRC >> Client >> Index.ts, when a startDate is in the future, the text should read "not available xx-xx days from ${locationConfig.startDate}". Code below. 

 log.info(
            `${location.Name} is not Available in ${
                locationConfig.sameDay ? 'the same day' : `around ${locationConfig.daysAround.start}-${locationConfig.daysAround.end} days from today! `
            } `,

**Comment by phamleduy04** [comment]
thank you for reporting the bug :)
