### ISSUE TITLE
Doesn't keep checking for locations if none is found

### ISSUE THREAD

**Issue by wmortume** [phamleduy04/texas-dps-scheduler#12]
The `requestAvailableLocation` function should keep looping if it doesn't find any available locations that match the criteria. My nearest locations aren't always available so it ends up checking for dates with no locations.

![image](https://user-images.githubusercontent.com/36937310/193871331-6007d228-1190-4bcd-8da6-2691be916475.png)

Suggested adding a loop like this in the `run` method:
```
while (this.availableLocation == null || this.availableLocation.length == 0) {
    await this.requestAvailableLocation();
}
```

**Comment by phamleduy04** [comment]
Hi! Thank you for your response! I will fix it on the next commit :). Also, I think this will be better: 

> If the location is null or the array is empty, prompt the user can't find location within the criteria and exit the program :).

**Comment by wmortume** [comment]
> Hi! Thank you for your response! I will fix it on the next commit :). Also, I think this will be better:
> 
> >

Why exit the program if the location they're looking for doesn't always show up? They'll have to keep rerunning the program randomly until their location shows up.

**Comment by phamleduy04** [comment]
hm, how about increasing the miles request by 5 every time check to the API ?

**Comment by wmortume** [comment]
That won't resolve the issue if someone is only looking for locations within their criteria/preference. It can take minutes for the nearest locations to show up and they disappear quickly so you would want to keep checking frequently.

**Comment by phamleduy04** [comment]
Oh, I know what you mean! So this function only finds a location within the area and saves it to an array. Then the program will find an appointment base on that array.

Send request -> to get an array of location -> infinitive loop that array to check for appointments
