### ISSUE TITLE
probably user error or missing library, can't get it working

### ISSUE THREAD

**Issue by EvilKarn9** [phamleduy04/texas-dps-scheduler#122]
hi - need some help first time GH user - npm start gave errors of 'could not read package.json: Error ENOENT: no such file or directory, open '/workspaces/codespaces-blank/package,json' - tried npm install and got the same error

I used to be technical but haven't coded in years so I should be able to do this. I really need it as I just realized that my out of state license expired and I couldn't get an appointment for months from now, hope I can get this working.

I'm sure there's nothing wrong with the code, just my installation. 
![gh](https://github.com/phamleduy04/texas-dps-scheduler/assets/173328976/60b6b642-a10b-4a37-bf7a-84977e6cd474)

**Comment by phamleduy04** [comment]
on the left pane, I dont see any code and the codespace name is `codespace-blank`. I think you create a blank codespace instead of the codespace with my project on it

**Comment by EvilKarn9** [comment]
thank you for your reply, and while I couldn't get it working on GH, I was able to use it on Replit. Please delete anything I may have mistakenly put there.  I was able to get my DPS appointment. Thanks again for your help and code.

**Comment by phamleduy04** [comment]
Sure no problem!
