### ISSUE TITLE
Code may not be running as I need it to?

### ISSUE THREAD

**Issue by girijalaxmiiyer** [phamleduy04/texas-dps-scheduler#126]
<img width="1470" alt="Screenshot 2024-07-07 at 6 56 13 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/138242453/25cf1dcb-44d1-4abb-b638-27496ec95f41">
Hi phamleduy!

First off, thank your for the service through your script in helping with the scheduling.

I am trying to run this code and even if I set the same day constraint to 'false', my output shows as 'same day appointment not available'. I am running this script on a sunday.

Could you please help?

**Comment by phamleduy04** [comment]
Did you change the config file after or before you run the bot?
