### ISSUE TITLE
'ERR_TLS_CERT_ALTNAME_INVALID'

### ISSUE THREAD

**Issue by dhrubabanerjee** [phamleduy04/texas-dps-scheduler#130]
I am getting a new error I was not seeing last week when I tried running this. Wondering if this is related to the Microsoft issues on Friday. 

```
[07/22/2024 11:43:33] Requesting Available Location....
Error: Hostname/IP does not match certificate's altnames: Host: publicapi.txdpsscheduler.com. is not in the cert's altnames: DNS:*.txSchedulingAppServiceEnvironment.p.azurewebsites.us, DNS:*.scm.txSchedulingAppServiceEnvironment.p.azurewebsites.us, DNS:txSchedulingAppServiceEnvironment.scm.p.azurewebsites.us
```
and
```
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:871:12) {
  code: 'ERR_TLS_CERT_ALTNAME_INVALID',
  reason: "Host: publicapi.txdpsscheduler.com. is not in the cert's altnames: DNS:*.txSchedulingAppServiceEnvironment.p.azurewebsites.us, DNS:*.scm.txSchedulingAppServiceEnvironment.p.azurewebsites.us, DNS:txSchedulingAppServiceEnvironment.scm.p.azurewebsites.us",
  host: 'publicapi.txdpsscheduler.com',
  cert: {
    subject: [Object: null prototype] {
      C: 'US',
      ST: 'Washington',
      L: 'Redmond',
      O: 'Microsoft Corporation',
      CN: '*.txSchedulingAppServiceEnvironment.p.azurewebsites.us'
    },
    issuer: [Object: null prototype] {
      C: 'US',
      O: 'DigiCert Inc',
      CN: 'DigiCert SHA2 Secure Server CA'
    },
    subjectaltname: 'DNS:*.txSchedulingAppServiceEnvironment.p.azurewebsites.us, DNS:*.scm.txSchedulingAppServiceEnvironment.p.azurewebsites.us, DNS:txSchedulingAppServiceEnvironment.scm.p.azurewebsites.us',
    infoAccess: [Object: null prototype] {
      'OCSP - URI': [Array],
      'CA Issuers - URI': [Array]
    },
    ca: false,
```
..and on and on.

Any ideas on what to do?

**Comment by texasdps** [comment]
getting the same

**Comment by thitganuong** [comment]
Me too
<img width="1658" alt="Screen Shot 2024-07-22 at 08 48 27" src="https://github.com/user-attachments/assets/bd5d8e7e-a70d-487d-8ee7-ba30cd77239a">

**Comment by phamleduy04** [comment]
Just test it got the same issue, seems like DPS issue. Will fix soon ;)

**Comment by phamleduy04** [comment]
v3.0.0 has been released and fixed this problem. Can you guys check? @thitganuong @dhrubabanerjee

**Comment by dhrubabanerjee** [comment]
Cool! do we need to do something specific to load v3.0.0? when I just run the config file it doesn't seem to work?

**Comment by phamleduy04** [comment]
Yes. If you are in github codespace you can use command "git pull" to load in. Make sure when you run npm run start it show "running dps v3.0.0" @dhrubabanerjee

**Comment by dhrubabanerjee** [comment]
Great! it's working in that it's running dis v3.0.0 but I keep getting this timeout error. Do you think it's related or a separate thing?
<img width="927" alt="image" src="https://github.com/user-attachments/assets/eab8f127-ded8-41e1-bfe7-c3eb972badf4">

Thank you so much for creating this and looking into this so quickly @phamleduy04

**Comment by phamleduy04** [comment]
No problem! About the issue, try to increase your `headersTimeout` to `30000` on your `config.yml`

**Comment by dhrubabanerjee** [comment]
It's working for me now and showing running ups v3.0.0! Thank you so much for creating this and looking into this so quickly @phamleduy04
