### ISSUE TITLE
Code doesn't work when I run

### ISSUE THREAD

**Issue by ORELSEPREPARETODIE** [phamleduy04/texas-dps-scheduler#132]
![image](https://github.com/user-attachments/assets/30b4139b-3c7b-49db-97ff-7ea42b8a7b0d)

Hi phaleduy! thank you for creating and sharing this code!
I know it works for most of the people, but some reason, I run into this issue
Could you please help me?

**Comment by phamleduy04** [comment]
The config file have some issue at line 41. seems like it is missing some spaces or tabs. You can find and fix it, or you can delete the config file and recreate again

**Comment by ORELSEPREPARETODIE** [comment]
Hi, I tried doing that, but it still doesn't work. Do you mind taking a look for me
![image](https://github.com/user-attachments/assets/ed14c003-ac6f-42b6-a967-996c7cc15b61)

**Comment by phamleduy04** [comment]
My bad, start date should be null or a date in MM/DD/YYYY format

**Comment by ORELSEPREPARETODIE** [comment]
ty! it worked

**Comment by jaiklmaooooo** [comment]
I'm having the same problem but I did everything you said. 
![Screenshot 2024-08-13 175917](https://github.com/user-attachments/assets/f5152def-8ae2-4822-ba1f-b23db3bc0b10)
