### ISSUE TITLE
Error: getaddrinfo ENOTFOUND apptapi.txdpsscheduler.com

### ISSUE THREAD

**Issue by de11is7** [phamleduy04/texas-dps-scheduler#139]
Set up config and ran on both GitHub codespaces and on local machine and received the following error no matter what parameters were used in the location section of the yaml file.

Error: getaddrinfo ENOTFOUND apptapi.txdpsscheduler.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'apptapi.txdpsscheduler.com'
}

**Comment by hari1318** [comment]
Looks like DSP site down. Maybe that’s the issue?

**Comment by phamleduy04** [comment]
This might be a sign that the official DPS scheduler going to introduce breaking change to the current app. I will monitor this.
