### ISSUE TITLE
Add a Preferred Time slot

### ISSUE THREAD

**Issue by tapabrata19** [phamleduy04/texas-dps-scheduler#14]
Like we have the preferred day, can we have a preferred time slot as well? So that the bot looks for a specific time window. 
e.g. 8am-10am, 10am-12pm, 12pm-2pm, 2pm-4pm, 4pm-6pm

**Comment by phamleduy04** [comment]
I have thought about this, but I don't really know the best way to implement this. But I will try my best on next update :)

**Comment by phamleduy04** [comment]
Hey @tapabrata19, I need your help :)

 Like I said before, I don't really know what is the best way to implement this. I have ideas like this

1. User will provide an array of their wanted time:
-  Example: `["2pm - 4pm"]`
- Format per element: `<time><am/pm> - <time><am/pm>`

Not sure it will work but let me know if you have a better way to implement this. Thank you :)

**Comment by yusufqxzi** [comment]
do this

**Comment by WilsonAkalol** [comment]
This should have always been added. I know you want the closest appointment but arbitrarily assigning the time value is annoying because what if you have work in the morning hours but free in the later hours?
