### ISSUE TITLE
ERROR 403

### ISSUE THREAD

**Issue by SSPlusUltra** [phamleduy04/texas-dps-scheduler#142]
![config yml - texas-dps-scheduler - Visual Studio Code  Administrator  29-07-2024 09_48_12 (1)](https://github.com/user-attachments/assets/52af279f-3635-4ba3-9255-d31d0bd8146e)

I think its getting blocked when its trying to book the appointment after finding it. So it works till it finds the appointment and then we get this error

**Comment by rickmania382** [comment]
Fails after 3 attempts. It was a good run bois.
Thanks captain Duy Pham Le!

**Comment by SSPlusUltra** [comment]
@rickmania382 I just got an appointment lol, still works but cant go as long as before

**Comment by thitganuong** [comment]
I run just a little bit and got the same error, retry but not work

**Comment by Shahomie** [comment]
I'm also getting the same error

**Comment by phamleduy04** [comment]
are you using v3.1.0?

**Comment by Shahomie** [comment]
> are you using v3.1.0?

Yes, I ran the git pull, npm install, and npm update commands. After doing so, I ran npm run start. The code will run for a few seconds and then the error will keep coming up until it stops all together after 3 times.

**Comment by SharvaParalkar** [comment]
![image](https://github.com/user-attachments/assets/b7ba9571-f736-4061-8952-b47d0a072cbd)

same thing happening, using 3.1.0

**Comment by phamleduy04** [comment]
i got that error randomly, sometimes the request passing got stuck with 403

**Comment by rickmania382** [comment]
FYI. The app has no issues with booking the appointment once found. It is not hitting "/api/AvailableLocation" after three attempts.
Yesterday's update did something.

**Comment by phamleduy04** [comment]
The error like @SSPlusUltra got I think that he got IP banned, try to use a VPN to see if it works.

**Comment by phamleduy04** [comment]
@rickmania382 ty. I think they implement some kind of rate limit

**Comment by SharvaParalkar** [comment]
increased interval from 10000 to 30000 it's running for longer now and hasn't stopped working yet

**Comment by phamleduy04** [comment]
just implement some kind of workaround for the rate limit. Will need to find permanent fix

**Comment by zerowebcorp** [comment]
DPS web team is getting smarter.

**Comment by Shahomie** [comment]
> DPS web team is getting smarter.

Instead making things harder for people, they should start hiring more and fix the backlog of months of no appointment

**Comment by Shahomie** [comment]
I was able to get an appointment even though the error codes are coming up
![image](https://github.com/user-attachments/assets/1897ed4b-e318-4315-b53d-d92b96b06d5f)

**Comment by sumanthdaruvuri** [comment]
@Shahomie 
Garland Mega Center doesn't even come on my location list despite me putting it's zipcode.

**Comment by AryanPillai2007** [comment]
@phamleduy04  thank you so much for your help, I managed to get a spot! 
![CleanShot 2024-07-29 at 12 46 51@2x](https://github.com/user-attachments/assets/a39ecd19-d6ae-49e1-90ac-9655cd8c3230)

**Comment by phamleduy04** [comment]
great to see the app work again :). Will try to find a fix for those rate limit, maybe better queue management something

**Comment by thitganuong** [comment]
I think this error happened when you scan over 2 persons/request in the same time.

**Comment by AsadMoulviDev** [comment]
Hey, I keep getting rate-limited as anyone tried with a VPN ?

**Comment by itsmateen** [comment]
Hey anyone getting the following error since morning.

[07/31/2024 1:35:40] Requesting Available Location....
/home/runner/texas-dps-scheduler/src/Client/index.ts:152
            log.error(`No Available location found! Nearest location is ${response[0].Distance} miles away! Please change your config and try again!`);
                                                                                      ^
TypeError: Cannot read properties of undefined (reading 'Distance')
    at TexasScheduler.requestAvailableLocation (/home/runner/texas-dps-scheduler/src/Client/index.ts:152:87)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TexasScheduler.run (/home/runner/texas-dps-scheduler/src/Client/index.ts:63:9)

**Comment by itsmateen** [comment]
> Hey, I keep getting rate-limited has anyone tried with a VPN ?

Untill last night it was working good with me even without VPN

**Comment by Tvu239** [comment]
I keep getting 403 status code and rate limit now and I cant even log into the website anymore. 
![Screenshot 2024-07-31 084953](https://github.com/user-attachments/assets/9c47f8c6-e758-4e39-950b-e6000618eebc)

**Comment by itsmateen** [comment]
> I keep getting 403 status code and rate limit now and I cant even log into the website anymore. ![Screenshot 2024-07-31 084953](https://private-user-images.githubusercontent.com/169959839/353856852-9c47f8c6-e758-4e39-950b-e6000618eebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzUzNTUsIm5iZiI6MTcyMjQzNTA1NSwicGF0aCI6Ii8xNjk5NTk4MzkvMzUzODU2ODUyLTljNDdmOGM2LWU3NTgtNGUzOS05NTBiLWU2MDAwNjE4ZWViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNDEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzhmMDZkMmUxMWUxMzI3MDk1Yjc2ODcxYWQwOTBjMGQ1YjhlNzM3NjA5ODU3Y2MxYjg1OGIyMmE2ZGQ3M2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwhStR91Mm4qpwlG2oF0p13tKipN3xOG4GD8bxEOy5Q)

yea they have implemented the IP banned soo give it 5 mins and try again it would work. i tried this way and it worked with me

**Comment by Tvu239** [comment]
> > I keep getting 403 status code and rate limit now and I cant even log into the website anymore. ![Screenshot 2024-07-31 084953](https://private-user-images.githubusercontent.com/169959839/353856852-9c47f8c6-e758-4e39-950b-e6000618eebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzUzNTUsIm5iZiI6MTcyMjQzNTA1NSwicGF0aCI6Ii8xNjk5NTk4MzkvMzUzODU2ODUyLTljNDdmOGM2LWU3NTgtNGUzOS05NTBiLWU2MDAwNjE4ZWViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNDEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzhmMDZkMmUxMWUxMzI3MDk1Yjc2ODcxYWQwOTBjMGQ1YjhlNzM3NjA5ODU3Y2MxYjg1OGIyMmE2ZGQ3M2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwhStR91Mm4qpwlG2oF0p13tKipN3xOG4GD8bxEOy5Q)
> 
> yea they have implemented the IP banned soo give it 5 mins and try again it would work. i tried this way and it worked with me

Its been like this since yesterday, should I give it more time or am I cooked

**Comment by itsmateen** [comment]
No you are good just give sometime

**Comment by santiago-brent** [comment]
I am also getting rate-limited 403 errors, VPN results in same thing. Did we get caught? XD

**Comment by aphyio** [comment]
still getting rate limited 403 errors, vpn aswell does nothing

**Comment by shahvaibhavutd** [comment]
I tried running raw request via Postman and that looks to be working fine, just fyi

**Comment by santiago-brent** [comment]
> I tried running raw request via Postman and that looks to be working fine, just fyi

Could you walk us through the setup process? Sorry, I'm a hardware guy.

**Comment by shahvaibhavutd** [comment]
@santiago-brent It very manual process where you have to make every single request at once, I wouldn't recommend it since this solution works well (given when your IP is not perm banned).

**Comment by phamleduy04** [comment]
track this issue at #156
