### ISSUE TITLE
uable to book when find spot

### ISSUE THREAD

**Issue by yoyoy74662000** [phamleduy04/texas-dps-scheduler#144]
![image](https://github.com/user-attachments/assets/88dc0e74-8f23-400c-b042-f738b0719fad)

**Comment by yoyoy74662000** [comment]
Just booked successfully.
![image](https://github.com/user-attachments/assets/c9296cb2-4f20-49e9-be6f-e3706c862366)

**Comment by phamleduy04** [comment]
duplicate #142
