### ISSUE TITLE
Unable to find the location

### ISSUE THREAD

**Issue by itsmateen** [phamleduy04/texas-dps-scheduler#150]
[07/31/2024 12:17:48] Requesting Available Location....
/home/runner/texas-dps-scheduler/src/Client/index.ts:152
            log.error(`No Available location found! Nearest location is ${response[0].Distance} miles away! Please change your config and try again!`);
                                                                                      ^
TypeError: Cannot read properties of undefined (reading 'Distance')
    at TexasScheduler.requestAvailableLocation (/home/runner/texas-dps-scheduler/src/Client/index.ts:152:87)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TexasScheduler.run (/home/runner/texas-dps-scheduler/src/Client/index.ts:63:9)

**Comment by phamleduy04** [comment]
This is expected if the official scheduler doesn't return any locations. I will need to write this error-handling case.

**Comment by saurabhjain0596** [comment]
Getting the same issue. Even after putting miles: 100

**Comment by gautham50050** [comment]
I have been getting the same message even though I have many DMVs close by, but it doesn't seem to recognize them.

**Comment by itsmateen** [comment]
Gautham, as of now code has some issues while pulling up the location, give them sometime to look into it. but the official site is working as usual with lot of security features enabled ( i believe )..

**Comment by gautham50050** [comment]
Alright thanks

**Comment by itsmateen** [comment]
any update Duy Pham  ???

**Comment by adamqazi** [comment]
I encountered the same issue and along with another one:
- When I set `zipCode` and `pickDPSLocation` to `false` in the `config.yml`, I get the error mentioned above
- When I set `pickDPSLocation` to `true`, it exits with the error `ERROR: You must choose at least one location!` without showing the prompt to choose the location

To check if the container was having trouble reading the input from the host env, I mounted the config file and executed commands within the container but I received the same output:
```
=> docker run -it -v "./config.yml:/home/container/config.yml" 4e0f1f6834ea bash
root@71d49469c432:/home/container# node index.js
[08/02/2024 4:10:39] WARNING -> Invalid date in config.yml, using current date
[08/02/2024 4:10:39] Texas Scheduler v3.1.1 is starting...
[08/02/2024 4:10:39] Requesting Available Location....
[08/02/2024 4:10:39] ERROR: You must choose at least one location!
```

I also tried increasing the radius, `miles`, but that didn't resolve the issue either

**Comment by FractalIceCream** [comment]
Yea encountering this issue as well. Curious if the api endpoint has been moved or changed because I tried checking the response from the request and returns null. Actually a quick fix, I was able to get a response by hard coding a fixed CityName (ex: Dallas) under the payload if that helps anybody.

**Comment by srisai-p** [comment]
@FractalIceCream where did you hardcode the city name

**Comment by adamqazi** [comment]
there is a function, `getAllLocationFromZipCodes`, seems like you can update the payload and set the city there

**Comment by phamleduy04** [comment]
Update, there is a fix made by @jaymit123 which supports city name to the config.yml. use `v4.2.0` to get this support.

Also thanks @FractalIceCream for mentioning this also
