### ISSUE TITLE
403 status code loop

### ISSUE THREAD

**Issue by akno3** [phamleduy04/texas-dps-scheduler#152]
outputting 
[08/01/2024 9:10:44] WARNING -> Got 403 status code
[08/01/2024 9:10:44] WARNING -> Got rate limited, sleep for 10s...
[08/01/2024 9:10:54] WARNING -> Got 403 status code
[08/01/2024 9:10:54] WARNING -> Got rate limited, sleep for 10s...
[08/01/2024 9:11:04] WARNING -> Got 403 status code
[08/01/2024 9:11:04] WARNING -> Got rate limited, sleep for 10s...
[08/01/2024 9:11:14] WARNING -> Got 403 status code
[08/01/2024 9:11:14] WARNING -> Got rate limited, sleep for 10s...
forever.... any fix?

**Comment by shahvaibhavutd** [comment]
I'm getting this since 31st July, it worked fine when I ran it first time on 29th July. Not sure what happened between now and then.

**Comment by thitganuong** [comment]
i think your ip was permanently banned. need to use vpn.

**Comment by akno3** [comment]
> i think your ip was permanently banned. need to use vpn.

any recommendations? would using a new device work also?

**Comment by Shahomie** [comment]
I just used a VPN, I'm still getting a rate lock. GG bois

**Comment by Shahomie** [comment]
![image](https://github.com/user-attachments/assets/b8be6fdd-673a-4963-a54b-787ccc4d996d)
![image](https://github.com/user-attachments/assets/1fb6efa4-57af-4da2-b3cc-03a15a6d64d4)

**Comment by thitganuong** [comment]
<img width="903" alt="Screen Shot 2024-08-02 at 14 04 40" src="https://github.com/user-attachments/assets/eba2f2b8-5f1f-4cbc-98a5-3909adb1bac2">
I used multiple VPN but cannot go to next step from browser as well.

**Comment by Shahomie** [comment]
> <img alt="Screen Shot 2024-08-02 at 14 04 40" width="903" src="https://private-user-images.githubusercontent.com/4476313/354698700-eba2f2b8-5f1f-4cbc-98a5-3909adb1bac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjU5MDEsIm5iZiI6MTcyMjYyNTYwMSwicGF0aCI6Ii80NDc2MzEzLzM1NDY5ODcwMC1lYmEyZjJiOC01ZjFmLTRjYmMtOThhNS0zOTA5YWRiMWJhYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTkwNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZlMTg1Zjk0MDZlMjYzYTVmMzhhMzc2ZTdhNDY3ZDg0Y2YzZDI4M2NjMjUyNDlhMDllY2E0NzcxYzY3YmI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xQnxkYPq__zS7XOQJOBDxGEqA2Jt19csnNkFVW40aP8"> I used multiple VPN but cannot go to next step from browser as well.

Yes that's it DPS has put up too many blockers up, the scheduler might not work anymore.

**Comment by thitganuong** [comment]
https://downforeveryoneorjustme.com/dps.texas.gov

System is down now.

**Comment by Shahomie** [comment]
> https://downforeveryoneorjustme.com/dps.texas.gov
> 
> System is down now.

Yea I just checked after you mentioned it, checked their website, its down for maintenance
