### ISSUE TITLE
Config File is not valid

### ISSUE THREAD

**Issue by Shahomie** [phamleduy04/texas-dps-scheduler#155]
Not sure why I'm getting this error message but it keeps saying config file is not valid?

`@Shahomie ➜ /workspaces/texas-dps-scheduler (main) $ npm run start

> texas-dps-scheduler@3.1.1 start
> ts-node --transpile-only src/index.ts

[08/02/2024 4:17:28] WARNING -> Invalid date in config.yml, using current date
[08/02/2024 4:17:28] ERROR: Config file is not valid
ZodError: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "string",
    "path": [
      "appSettings",
      "maxRetry"
    ],
    "message": "Expected number, received string"
  }
]
    at Object.get error [as error] (/workspaces/texas-dps-scheduler/node_modules/zod/lib/types.js:55:31)
    at ZodObject.parse (/workspaces/texas-dps-scheduler/node_modules/zod/lib/types.js:160:22)
    at parseConfig (/workspaces/texas-dps-scheduler/src/Config/index.ts:28:26)
    at TexasScheduler.<instance_members_initializer> (/workspaces/texas-dps-scheduler/src/Client/index.ts:38:32)
    at new TexasScheduler (/workspaces/texas-dps-scheduler/src/Client/index.ts:47:5)
    at Object.<anonymous> (/workspaces/texas-dps-scheduler/src/index.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.m._compile (/workspaces/texas-dps-scheduler/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (/workspaces/texas-dps-scheduler/node_modules/ts-node/src/index.ts:1621:12) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'string',
      path: [Array],
      message: 'Expected number, received string'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'string',
      path: [Array],
      message: 'Expected number, received string'
    }
  ]
}
@Shahomie ➜ /workspaces/texas-dps-scheduler (main) $ `

**Comment by adamqazi** [comment]
please share the config file you are using, remove any private information before sharing

**Comment by Shahomie** [comment]
personalInfo:
  # Load from environment secret to prevent personal info leaking
  # If you are using replit free plan, set this true
  # Then add your info to the secrets section
  loadFromEnv: false

  # if loadFromEnv is true, anything in personalInfo beside typeId is ignored
  firstName: ''
  lastName: ''
  # Date of birth (MM/DD/YYYY)
  dob: ''
  # Use real email to get appointment infomation
  email: ''
  # Not really needed but good to have a real one
  lastFourSSN: ''
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)
  phoneNumber: ''

  # Serivce you needed at DPS. Check the full list on https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list
  # If you need to apply for Texas DL you don't need to change it
  typeId: 71

location:
  # Zipcode of your location. Can add more DPS location by using ',' for multiple zipcode
  zipCode: ['75023']
  # Choose your DPS location by yourself when running the application if set to true
  pickDPSLocation: true
  # Get appointment from all DPS location by distance from the zipcode, will auto skip this when pickDPSLocation is true
  miles: 15
  # Put empty [''] for any day
  # DPS is closed on weekends, so you can't book on Saturday and Sunday
  preferredDays: ['']
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: true
  # Put how many day from today you want to book from start to end (7 is a good number)
  daysAround:
    ## Start date: start and end will start counting from this date
    # MM/DD/YYYY format, if blank will use current date
    # If the date input is invalid or in the past, the app will automatically use the current date as start date
    startDate:
    start: 0
    end: 7
  # Put what time you want to book
  timesAround:
    # Number in 24h format, start = 6 and end = 18 means get appointment between 6 AM - 6 PM
    start: 8
    end: 18

appSettings:
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: true
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 30000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 3n

**Comment by adamqazi** [comment]
you have a typo in the value for `maxRetry`, it should be `3` and not `3n`

**Comment by Shahomie** [comment]
> you have a typo in the value for `maxRetry`, it should be `3` and not `3n`

It's working now thanks for the help!
