### ISSUE TITLE
Getting Error: Unauthrorized

### ISSUE THREAD

**Issue by owaisehmed** [phamleduy04/texas-dps-scheduler#156]
Need help fixing this. Anyone getting the same?

<img width="556" alt="Screenshot 2024-08-03 at 9 52 08 AM" src="https://github.com/user-attachments/assets/8b1496ee-054e-4650-a904-a3c123eeeae5">

**Comment by SharvaParalkar** [comment]
Same here, looks like they updated the site again yesterday

**Comment by Shahomie** [comment]
The site is still down for maintenance, they're def getting better

**Comment by SharvaParalkar** [comment]
check to see if they're down on a different device, every other device for me works except the one i've been using to get appts

**Comment by Shahomie** [comment]
> check to see if they're down on a different device, every other device for me works except the one i've been using to get appts

Okay, I'll check now, just checked my phone says site down for maintenance.

**Comment by christianmendoza** [comment]
It looks like they've added Authorization to the request headers

<img width="481" alt="Screenshot 2024-08-03 at 10 10 27" src="https://github.com/user-attachments/assets/5a431cdb-ddf0-42db-9d01-8c276dad72f2">

**Comment by Shahomie** [comment]
Damn yea you were right, they're targeting specific devices, I can't access the site on my laptop or phone, only my ipad

**Comment by itsmateen** [comment]
even im getting the authorization error, the site is working on all my devices but they added the authorization.

**Comment by zerowebcorp** [comment]
New authorization header implemented. Looks like they are targetting these bots. Thanks to the 13 year old kid Soumya Nandyala for the publicity so that dps knew about these bots.

**Comment by Shahomie** [comment]
> New authorization header implemented. Looks like they are targetting these bots. Thanks to the 13 year old kid Soumya Nandyala for the publicity so that dps knew about these bots.

Always some kid that gotta ruin everything

**Comment by phamleduy04** [comment]
Will be fixed on new release. Initially I have a way in mind but need further testing.

**Comment by phamleduy04** [comment]
I will start working on it next week 👍

**Comment by phamleduy04** [comment]
I just pushed `v4.0.0-beta1` on auth branch. But here is a catch:

- There is an extra step to do to get the auth token
- I need to research when the auth token is expired.
- I need to code the automated way to get the auth token (on development right now).

The code you can get is located [here](https://github.com/phamleduy04/texas-dps-scheduler/tree/auth)
The wiki how you can get auth token is on the [wiki](https://github.com/phamleduy04/texas-dps-scheduler/wiki/How-to-get-Auth-Token)

**Comment by phamleduy04** [comment]
FYI, As far as I know, the auth token isn't validated/signed by IP so you can get it on your IP and use it on codespaces/different IP.

**Comment by romanvolkov650** [comment]
> FYI, As far as I know, the auth token isn't validated/signed by IP so you can get it on your IP and use it on codespaces/different IP.

Thanks for quick update, just tested it, it works (auto get auth token) and search for available slots, but after some time token expires and I'm getting 401, and script stops. Can you please add re-auth on 401?

**Comment by phamleduy04** [comment]
@romanvolkov650 try [4.1.0](https://github.com/phamleduy04/texas-dps-scheduler/tree/4.1.0), new auth method + re-auth

**Comment by phamleduy04** [comment]
fixed in v5.0.0
