### ISSUE TITLE
Domain not existing: publicapi.txdpsscheduler.com

### ISSUE THREAD

**Issue by xoudels** [phamleduy04/texas-dps-scheduler#157]
<img width="802" alt="image" src="https://github.com/user-attachments/assets/df4fa4c0-cbc9-4878-95c6-37cc116d07b6">

Was the api endpoint changed or something? I started getting this a few days ago. With a quick nslookup I was able to confirm that the domain is non existing. Not a Node JS guy so I am not sure if I am looking in the right direction. Any help would be highly appreciated.

**Comment by phamleduy04** [comment]
track issue at #156
