### ISSUE TITLE
403 Error Code even with Captcha

### ISSUE THREAD

**Issue by Alecmay101** [phamleduy04/texas-dps-scheduler#161]
![image](https://github.com/user-attachments/assets/9fb7c198-717d-4dc4-905d-6e9198fba50f)

**Comment by lincantcode** [comment]
i have the same problem

**Comment by romanvolkov650** [comment]
403 not depends on captcha, it's just requests limit, just increase interval in app settings

**Comment by phamleduy04** [comment]
403 also mean `your IP is being blocked`. Try to create a new codespace to refresh IP address

**Comment by Alecmay101** [comment]
Creating new code space resolved issue
