### ISSUE TITLE
Error: getaddrinfo ENOTFOUND publicapi.txdpsscheduler.com

### ISSUE THREAD

**Issue by mrsooner1** [phamleduy04/texas-dps-scheduler#165]
getting this error this morning 

Error: getaddrinfo ENOTFOUND publicapi.txdpsscheduler.com

**Comment by phamleduy04** [comment]
are you using the old version? The latest version as of Aug 8 is v4.1.0

**Comment by tometom235** [comment]
getting this error as well 

![image](https://github.com/user-attachments/assets/93663809-a644-4f2f-9416-befa1eadb3a8)

**Comment by phamleduy04** [comment]
Old version, latest should be v4 now instead of v2
