### ISSUE TITLE
Code ends when no dates are avaliable

### ISSUE THREAD

**Issue by joswayz** [phamleduy04/texas-dps-scheduler#168]
![Screenshot 2024-08-11 211548](https://github.com/user-attachments/assets/83b629fa-4df4-4843-bdad-785df8e92175)
![Screenshot 2024-08-11 211106](https://github.com/user-attachments/assets/0ebcd4b5-e6ac-4551-a625-3490f4959637)

Hello right now there is not a single availability for Austin and instead of retrying until there is, the code just ends and I have to start it again manually.

**Comment by phamleduy04** [comment]
Have you tried to use the city name option on config.yml instead of zipcode?
