### ISSUE TITLE
.

### ISSUE THREAD

**Issue by satyadevkalakonda** [phamleduy04/texas-dps-scheduler#17]

**Comment by SmartHustleW** [comment]
same issue here

**Comment by phamleduy04** [comment]
did you guys using replit by any chance? @satyadevkalakonda @SmartHustleW

**Comment by phamleduy04** [comment]
try to set `cancelIfExist` to `false` on config.yml file see if it helps

**Comment by SmartHustleW** [comment]
Will try Thanks
