### ISSUE TITLE
Zipcode limited in Central Texas

### ISSUE THREAD

**Issue by TheRegent76** [phamleduy04/texas-dps-scheduler#170]
When I input the actual zipcodes for DPS locations in Austin, it only registers the Pflugerville Megacenter and outside of Austin according to the set miles. 
"WARNING -> No location found for zipcode: 78750" etc.

Please advise?

**Comment by asvin-kumar** [comment]
I'm seeing a similar warning too. Running it locally. It's not really finding any location even with a 100 mi radius. 
Plus I see this error which I think is because no locations were found:

>  log.error(`No Available location found! Nearest location is ${response[0].Distance} miles away! Please change your config and try again!`);

Any ideas/suggestions @phamleduy04 ?

**Comment by phamleduy04** [comment]
@TheRegent76 , @asvin-kumar . Can you try to use the CityName option on config.yml instead of zipcode?

**Comment by TheRegent76** [comment]
@phamleduy04 I tried 'Austin' this morning and it returned New Braunfels, 'which is 43 miles away'. The DPS scheduler website returns 'Austin South', when 'Austin' is inputted, and 'Pflugerville, Austin South, Temple, Killeen, Cameron' when Zip and Pflugerville are inputted.  Pflugerville has a mega center, but Austin has 2 more locations that are not listed in the DPS website right now. The Georgetown area also has a DPS center and is closer to Austin than the other locations they list.

Could the program be returning less choices because DPS is somehow restricting the available offices internally?

**Comment by phamleduy04** [comment]
@TheRegent76 , Yes since the program is using the same DPS system as the official one, so if the official one is returning fewer cities, the app will returning the same data

**Comment by TheRegent76** [comment]
makes sense! thx
