### ISSUE TITLE
Getting Rate Limited for the Past Three days

### ISSUE THREAD

**Issue by gunareborn** [phamleduy04/texas-dps-scheduler#173]
I m trying to get an appointment for the past three days but I am always getting rate limited error. Tried from couple Machines and deleted and created New Code spaces, tried with multiple locations as well. Please let me know if anyone was able to book the appointment using this the last three days 
![image](https://github.com/user-attachments/assets/465ffa6f-da08-46e9-ae5b-50ff13577951)

**Comment by phamleduy04** [comment]
Details here https://github.com/phamleduy04/texas-dps-scheduler/issues/163#issuecomment-2275990711

**Comment by itsmateen** [comment]
i think they made new changes in auth token,

**Comment by phamleduy04** [comment]
fixed in v5.0.0
