### ISSUE TITLE
[Fri Aug 16] Maintenance watch 

### ISSUE THREAD

**Issue by phamleduy04** [phamleduy04/texas-dps-scheduler#174]
[Official DPS](https://public.txdpsscheduler.com/) is down for maintenance. Might introduce breaking changes to the app.

**Comment by phamleduy04** [comment]
https://github.com/phamleduy04/texas-dps-scheduler/issues/173#issuecomment-2295306836

Introduced breaking changes

**Comment by phamleduy04** [comment]
Will fix on next release

**Comment by dinocaofeng** [comment]
the [Official DPS](https://public.txdpsscheduler.com/) is back but seems not stable, and previously I could run scheduler on my laptop, but today it's start to face issue, could you help to check?
[08/18/2024 12:02:17] WARNING -> Got 403 status code
[08/18/2024 12:02:17] WARNING -> Got rate limited, sleep for 10s...

**Comment by zerowebcorp** [comment]
Don't you think dps team is watching this repository and incrementally making changes as we find workarounds?

**Comment by phamleduy04** [comment]
> Don't you think dps team is watching this repository and incrementally making changes as we find workarounds?

Yeah but since this repo is public there is nothing i can do

**Comment by TheRegent76** [comment]
Yes. I get in, request auth token, get 'abc' token - multiple times, then rate limited.

**Comment by Harshith-H-K** [comment]
Thank you so much for everything you do! @phamleduy04 .

**Comment by sasank2899** [comment]
is the code working today?

**Comment by sasank2899** [comment]
chill bruh! i was just askin

**Comment by phamleduy04** [comment]
Just take a look, they introduced new changes on the `/auth` endpoint which validated the captcha token correctly. There is some workaround about this since this might lead to use external service.

- Use a captcha solver service like 2captcha, anticaptcha, capsolver, etc... to use the service. It will cost money (1-3 bucks per 1000 requests depends on which service) - Which is pretty cheap since we only need to grab the auth token once in a while.
- (Local host only): Use puppeteer to automatically grab the auth token, which is expensive in computer resources but you don't have to pay for a 3rd party services.

**Comment by phamleduy04** [comment]
move this issue to #175
