### ISSUE TITLE
Request: More advanced "daysAround"

### ISSUE THREAD

**Issue by yusufqxzi** [phamleduy04/texas-dps-scheduler#21]
We are already able to choose how many days we want the appointment within. However, are we able to make more advanced changes do daysAround, for example, saying I want in appointment within 7-14 days from today?

**Comment by sudo-chan** [comment]
I would love to see this implemented as well. Could it also be implemented for distance as well? There is a specific DPS I would like to go to but its not the closest to me. It would be nice to set an optional min distance as a part of the filter too!

**Comment by phamleduy04** [comment]
@yusufqxzi added in #23.
