### ISSUE TITLE
Links not working for Driving test 901

### ISSUE THREAD

**Issue by edwinreyna7** [phamleduy04/texas-dps-scheduler#30]
Links for driving test not working as intended. 
TypeError: res.sort is not a function
    at /home/runner/texas-dps-scheduler-4/src/Client/index.ts:100:61
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TexasScheduler.requestAvaliableLocation (/home/runner/texas-dps-scheduler-4/src/Client/index.ts:98:55)
    at async TexasScheduler.run (/home/runner/texas-dps-scheduler-4/src/Client/index.ts:44:9)
exit status 1

**Comment by phamleduy04** [comment]
This is a documentation error. There is no such type of Driving test that has ID 901.

If you want to schedule a driving test, there are 6 types of Driving Tests

```
| 11 | CDL | 
| 21 | Class C | 
| 31 | Class M | 
| 51 | RV | 
| 61 | Public Safety | 
| 121 | Non-CDL Class A/Class B | 
```

Sorry for the confusion!

**Comment by phamleduy04** [comment]
The [wiki](https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list) also updated. Thanks again!

**Comment by phamleduy04** [comment]
Just for you to know you don't have to sponsor me. But if you want to I have a [Github Sponsor link](https://github.com/sponsors/phamleduy04)
