### ISSUE TITLE
Awesome app with minor issue - Deleting the Cache folder doesn't reset the locations

### ISSUE THREAD

**Issue by zakaryaalsaba** [phamleduy04/texas-dps-scheduler#36]
I used Replit, ran the app, and selected 5 locations nearby. Everything works fine.
When I tried to run the app again, I deleted the Cache folder but it kept selecting the locations that have been selected at the first step. It doesn't allow me to select the locations one more time.

Looks like this issue is not related to the app itself but maybe Replit. However, this app was successful to book an appointment for me. Awesome app.. Great work.. 5 STARS.. Thanks a lot.

**Comment by phamleduy04** [comment]
Just for clarification, did you deelete cache folder before running the app or after running the app?
