### ISSUE TITLE
Not  booking appointment

### ISSUE THREAD

**Issue by bournehunter** [phamleduy04/texas-dps-scheduler#46]
When it finds an open appointment it isn't booking it

**Comment by phamleduy04** [comment]
Can you try the newest release of the software?

Type `git pull` on the console/terminal or just delete the project and create it again (replit)

**Comment by phamleduy04** [comment]
I tested on the newest release and can get the appointment

![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/6de2c344-5ad2-4d41-b680-c3a9e8bdd0fe)
