### ISSUE TITLE
Thank you and  env question

### ISSUE THREAD

**Issue by ceciliacici** [phamleduy04/texas-dps-scheduler#49]
Thank you so much for this amazing project. I followed your youtube and created secrete info. However, I got this error message. 

[07/08/2023 9:29:58] Loading personal info from environment variables.
[07/08/2023 9:29:58] ERROR: Missing environment variables for personal info. Please refer to example.env file.
exit status 1

![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/139016593/1541bbd7-34b4-4511-955e-d7133da30187)

Can you please help?

Thank you,
Jiaxi

**Comment by phamleduy04** [comment]
your are missing some fields like `EMAIL` and `PHONENUMBER` at your secrets field

**Comment by ceciliacici** [comment]
It worked！thank you！

**Comment by phamleduy04** [comment]
no problem :D
