### ISSUE TITLE
error came up when it tried to schedule

### ISSUE THREAD

**Issue by fangzhang2008** [phamleduy04/texas-dps-scheduler#53]
--------------------------------------------------------------------------------
[07/15/2023 12:42:31] Plano is avaliable on 7/19/2023 9:00 AM
[07/15/2023 12:42:31] Slot hold successfully
[07/15/2023 12:42:31] Booking slot....
/home/runner/texas-dps-scheduler/src/Client/index.ts:265
            const appointmentURL = `https://public.txdpsscheduler.com/?b=${bookingInfo.Booking.ConfirmationNumber}`;
                                                                                               ^
TypeError: Cannot read properties of null (reading 'ConfirmationNumber')
    at TexasScheduler.bookSlot (/home/runner/texas-dps-scheduler/src/Client/index.ts:265:96)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TexasScheduler.holdSlot (/home/runner/texas-dps-scheduler/src/Client/index.ts:233:9)
exit status 1

**Comment by fangzhang2008** [comment]
This was using replit, when I tried it using node.js it worked fine.

**Comment by phamleduy04** [comment]
thank you for your report, i will take a look into this.

FYI in this step, the appointment has been booked successfully (I think so?) but somehow it can't get the confirmation number. 

You can log in to [Texas DPS](https://public.txdpsscheduler.com/) and try to enter the exact information in your `.env`/`config.yml` to check if it booked successfully or not.

**Comment by fangzhang2008** [comment]
I think it happened because I was trying to book for my wife and me at the same time using two instances of this program? It worked when I used individually using node.js. 

It was not a successful booking when i checked texas DPS when it gave me the error.

**Comment by phamleduy04** [comment]
> because I was trying to book for my wife and me at the same time using two instances of this program

did one of the program booked successfully?

**Comment by phamleduy04** [comment]
If one of the program is booked successfully I think two instances of the program are trying to secure the same appointment, and one will be returned an error while the other one successful.

**Comment by fangzhang2008** [comment]
Yes I was eventually able to book for both my wife and I. Thank you very
much for making this!!!!

**Comment by phamleduy04** [comment]
no problem 👍
