### ISSUE TITLE
Not loading on replit

### ISSUE THREAD

**Issue by HadeedKhan1** [phamleduy04/texas-dps-scheduler#54]
The old one worked fine, but the new version is not loading on replit. Forzen at this screen:
 esbuild index.ts --bundle --log-level=warning --outdir=./.build --outbase=. --sourcemap=inline --target=node16 --platform=node --format=cjs

**Comment by phamleduy04** [comment]
hi, try to delete the project and then clone again. it should work now :)

**Comment by HadeedKhan1** [comment]
thanks!

**Comment by HadeedKhan1** [comment]
hi! still not working

**Comment by phamleduy04** [comment]
okay, try again. This time replit will show this box like this

![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/af64db8e-facf-49b7-9b49-baf85bc401f1)

Just press done and setup everything will work now 👍

**Comment by HadeedKhan1** [comment]
works, thanks!
