### ISSUE TITLE
Program not running

### ISSUE THREAD

**Issue by tmbarron** [phamleduy04/texas-dps-scheduler#55]
Hi, first of all thanks for making this, we're in a pretty desperate pinch to schedule with the DPS asap so I was blown away that this exists. 

I've tried running it following your instructions perfectly, and keep getting stuck with the same result (pasted below) -- without it running fully or completing. It looks like a couple people in the YouTube comments weren't able to schedule either, going back a couple months now.

Thanks for any insight!

<img width="429" alt="Screen Shot 2023-07-23 at 9 19 14 AM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/140328646/81c9f9e7-ecdf-4a20-b295-42e06194ef9a">

esbuild index.ts --bundle --log-level=warning --outdir=./.build --outbase=. --sourcemap=inline --target=node16 --platform=node --format=cjs

**Comment by chandrachunduru** [comment]
I'm also having the same problem! I would love a solution this is so amazing!

**Comment by phamleduy04** [comment]
@tmbarron couple things you can try:
- Try to delete the project and then import again the same as #54.
- Or, don't press the run button, switch to console mode then type `npm run start`.

**Comment by Imhotep86** [comment]
@phamleduy04  - I am having similar issue. But tried your above options but no luck. It throws the compilation error when running 'npm run start' command.  Any idea I am missing something ?

> texas-dps-scheduler@1.6.3 start
> ts-node src/index.ts

/home/runner/texas-dps-scheduler/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/Client/index.ts:64:19 - error TS2345: Argument of type '(res: ExistBookingResponse[]) => ExistBookingResponse[]' is not assignable to parameter of type '(value: unknown) => ExistBookingResponse[] | PromiseLike<ExistBookingResponse[]>'.
  Types of parameters 'res' and 'value' are incompatible.
    Type 'unknown' is not assignable to type 'ExistBookingResponse[]'.

64             .then((res: ExistBookingResponse[]) => res.filter((booking: ExistBookingResponse) => booking.ServiceTypeId == this.config.personalInfo.typeId));
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Client/index.ts:91:16 - error TS18046: 'response' is of type 'unknown'.

**Comment by chandrachunduru** [comment]
Im also having that same issue as you @Imhotep86

**Comment by phamleduy04** [comment]
@Imhotep86 your issue moved to #58

**Comment by Imhotep86** [comment]
@phamleduy04  - Thank you for the quickest fix. Retried and works like a charm and already booked appointment for 8/7. Appreciate it and will share it with my circle... 

Kudos and Power of open source...!!!
