### ISSUE TITLE
Is there a way to set time slot when booking ? 

### ISSUE THREAD

**Issue by adityavb91** [phamleduy04/texas-dps-scheduler#57]
Is there a way to set time slot when booking ? 

For example:

hold slot if available slot time is after 10AM

**Comment by phamleduy04** [comment]
Not yet, but will implement soon on new version

**Comment by adityavb91** [comment]
Awesome thank you so much! you rock!

**Comment by phamleduy04** [comment]
@adityavb91, the feature has been added. Can you test it?

**Comment by adityavb91** [comment]
it is currently running with the preferred time slot .... waiting for it to hold slot ... I will keep you posted.

**Comment by phamleduy04** [comment]
Thank you 👍

**Comment by adityavb91** [comment]
Nice it works! Thank you so much! I think we can go ahead and close this out :)

**Comment by phamleduy04** [comment]
Thank you ;)
