### ISSUE TITLE
Exit Status 217  

### ISSUE THREAD

**Issue by gabscrotty** [phamleduy04/texas-dps-scheduler#59]
All information is followed and correct as per you tube video. 
Error that comes up is follows: 

tsx index.ts
sh: line 1: tsx: command not found 
exit status 217

**Comment by phamleduy04** [comment]
<img width="275" alt="Screen Shot 2023-08-10 at 2 04 06 AM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/8a71979c-abbf-474c-909b-72b0e563afe8">

- Please try to switch to "shell mode" then type `rm -rf node_modules && npm i`. 

- If the issue still occur, try to delete and try again. When it show a box look like this, press done and then start setting up your information like the video.

![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/b73c75ed-f235-4cf1-9bab-663d66b2ec9f)

**Comment by phamleduy04** [comment]
I just updated with new video how to setup [here](https://youtu.be/JT769XpTYJk)
