### ISSUE TITLE
"Miles" variable not working

### ISSUE THREAD

**Issue by loriannehess** [phamleduy04/texas-dps-scheduler#63]
The "miles" variable on line 30 of the config.yml file does not seem to be working. Because I really, really need an appointment within the next week and am willing to drive a couple of hours if needed, I put in my zip code and '100' for the miles variable, but it only returns the same 5 DMVs near me. I've also tried it with '300' miles, '200' miles, etc. and have the same result. To make sure its not an issue just with my zip code, I've tried others as well in far-away parts of the state but it only returns the 3-5 DMVs immediately around that zip code.

Thank you!

**Comment by phamleduy04** [comment]
This is DPS API limitation and this is nothing that I can do. The DPS API only returns max 5 locations.
