### ISSUE TITLE
Suggestion for clearer "Run on your computer" instructions

### ISSUE THREAD

**Issue by Deep903** [phamleduy04/texas-dps-scheduler#64]
Hello! You have a wonderful project here.

I think adding the following line to the "Run on your computer" instructions would be helpful.

Old instructions:
Run on your computer

- Ensure you installed [node.js](https://nodejs.org/en/) on your computer.
- Clone the repo
- Install dependencies
- Copy example.config.yml to config.yml and edit it to your preference.
- npm install
- npm run start

New:
Run on your computer

- Ensure you installed [node.js](https://nodejs.org/en/) on your computer.
- Clone the repo
- Install dependencies
- Copy example.config.yml to config.yml and edit it to your preference.
- **Copy example.env to .env and edit it to your preference.**
- npm install
- npm run start

**Comment by phamleduy04** [comment]
if you set `loadFromEnv` is true on `config.yml` then you will need to edit `.env` file. If not you can just edit the `config.yml` file and it will work 👍
