### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by Hardemanj87** [phamleduy04/texas-dps-scheduler#65]
Please help me work this. Can I be available for use on mobile devices?

**Comment by phamleduy04** [comment]
Did you check the [installation wiki](https://github.com/phamleduy04/texas-dps-scheduler/wiki/Installation) ?

**Comment by Hardemanj87** [comment]
Yes I tried to do the installation of the API and everything and the whole
copy and paste procedure I think is maybe what I'm having a problem with
really but I was also curious if it would work on a mobile browser or if I
have to use my laptop in order to copy and paste the API for the
scheduler???

**Comment by Hardemanj87** [comment]
I also watched the wikiHow instructions and the YouTube video after I tried
to install the API but I can't hear you very well in that video do you have
one that has a better sound quality on it

**Comment by phamleduy04** [comment]
I don't really try on a phone so I don't know if it does work or not. And sorry for the voice quality, I don't have other video to show how to do it, please try to increase the volume on the video 😭

**Comment by Hardemanj87** [comment]
What's the success rate if you add the API to that web address in order to
get the scheduler working.

**Comment by phamleduy04** [comment]
I don't know what you mean by "add the API to that web address". But the booking success rate depends on:

- The user have that appointment cancel that booking
- DPS open more booking slot at that day and time

**Comment by Hardemanj87** [comment]
Is there anyway that you could help me set up the appointment?

**Comment by phamleduy04** [comment]
The software is provided as-is, so I can't help you. Sorry about that.

**Comment by AdityaD27** [comment]
Hi, I did everything as mentioned in the video but when I click on run, I encounter this error - 
**_tsx index.ts
sh: line 1: tsx: command not found
exit status 127_**

Then I tried doing npm install and npm run start manually but then somehow I am not getting the webview so I can't access the url. Can you please help?

**Comment by phamleduy04** [comment]
@AdityaD27 Did you set `webserver` option to true on `config.yml` file?
