### ISSUE TITLE
Suggestions on rebooking

### ISSUE THREAD

**Issue by yuanz4** [phamleduy04/texas-dps-scheduler#68]
Great project! Trying it now!

Just one advice for a new feature. If there is an existing appointment and some available slots, maybe it can compare the date and only book if a sooner time slot is available. So if I let my program run background and it won't book several times and choose a later time if the earlier ones are taken by others.

And just curious how do you figure out all those API calls since they are not public. Do you just play around the DPS website and record all those APIs from browser develop tools?

Thanks!

**Comment by yuanz4** [comment]
Thanks for explaining that for me! The case I am thinking is like this which I am not sure whether will happen. There are 3 available slots in user desired time, naming them 1, 2, 3. And I make the program run for a while so it will query the server several times.

At first time it will book the slot 1. Then at second time the slot 2 is booked by others, but the program notices slot 3 is still available so it cancels slot 1 and book slot 3. Finally at third time the slot 1 is also taken by others and the program won't do anything. So in that case the program will book the last available time slot if there is some others competing with us.

But I think most users would like to book as soon as possible in their desired time window. I don't know whether that race condition will happen. Just some thoughts.

**Comment by phamleduy04** [comment]
There is also a case if you set `cancelIfExist` is `true` and you are using repl.it free plan with monitor services like cronjob and uptimerobot. The monitor service will request to repl.it and make the bot "restart" and start searching for new appointment again. It will cancel the existing appointment and go for the newer one it found based on the citeria.

The fix:  
- When the application done, delete the repl in repl.it and delete that entry on monitor services.
- Set `cancelIfExist` to `false`

**Comment by yuanz4** [comment]
I see, that make sense. And btw, your application helps me book a close time slot. Thanks sincerely!

**Comment by phamleduy04** [comment]
no problem, im glad you find the app useful :)
