### ISSUE TITLE
Help for running the project locally

### ISSUE THREAD

**Issue by AviBhatnagar22** [phamleduy04/texas-dps-scheduler#70]
I am trying to run the project locally. Are there any specific things I should know for this? I am following mostly the same instructions as the video, but I have webserver to false. I don't use any cron jobs or anything, I am just leaving it running. Is that a good way to get an appointment? I haven't had any success yet.

**Comment by phamleduy04** [comment]
How long have you left it running?

**Comment by AviBhatnagar22** [comment]
I have left it running for about 4-5 hours. But I just saw that new same-day appointments are released only at 7:30 am Mon-Friday, so I haven't ran it that time.
----
This is the config.yml

personalInfo:
  # Load from environment secret to prevent personal info leaking
  # If you are using replit free plan, set this true
  # Then add your info to the secrets section
  loadFromEnv: false

  # if loadFromEnv is true, anything in personalInfo beside typeId is ignored
  firstName: "My First Name"
  lastName: "My Last Name"
  # Date of birth (MM/DD/YYYY)
  dob: "DOB"
  # Use real email to get appointment infomation
  email: "my email"
  # Not really needed but good to have a real one
  lastFourSSN: "0000"
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)
  phoneNumber: "1234567890"

  # Serivce you needed at DPS. Check the full list on https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list
  # If you need to apply for Texas DL you don't need to change it
  typeId: 71

location:
  # Zipcode of your location
  zipCode: "75251"
  # Choose your DPS location by yourself when running the application if set to true
  pickDPSLocation: false
  # Get appointment from all DPS location by distance from the zipcode, will auto skip this when pickDPSLocation is true
  miles: 30
  # Put empty [''] for any day
  # DPS is closed on weekends, so you can't book on Saturday and Sunday
  preferredDays: [""]
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: false
  # Put how many day from today you want to book from start to end (7 is a good number)
  daysAround:
    start: 2
    end: 7
  # Put what time you want to book
  timesAround:
    # Number in 24h format, start = 6 and end = 18 means get appointment between 6 AM - 6 PM
    start: 6
    end: 18

appSettings:
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: false
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 20000
  # How many times to retry if the request to DPS server failled
  maxRetry: 3

# If you dont know what to change here, dont change it :)
webhook:
  # If your using Bluebubbles webhook/api put this to true otherwise, keep it false
  enable: false
  url: ""
  password: ""
  # phone number with country code (EX: +11111111111)
  phoneNumber: ""
  # private-api or apple-script
  sendMethod: "apple-script"
  # iMessage or SMS
  phoneNumberType: "SMS"
----
So I do have loadFromEnv set to false and am writing my info in the config.yml itself instead of having a .env file.

**Comment by phamleduy04** [comment]
how many locations did you choose? Also, this is a kinda bad time to schedule since the appointment is usually random open throughout the day

**Comment by phamleduy04** [comment]
I would recommend keeping it on until tonight, but if u can't keep the computer turned on until you get an appointment I would suggest you try the repl.it way.

**Comment by AviBhatnagar22** [comment]
So do you recommend I start it early morning?
Also, I did try the repl.it method. But the cron-job test run was giving me a 404 error with the webview link. What could be happening there? Also could you explain what the cron job is actually doing? Since the program does automatically keep retrying, why is cron job needed? Is it so that I can close the tab and cron job will keep querying it and keeping the repl active?

**Comment by phamleduy04** [comment]
repl.it free plan will force stop projects that are not active (coding/modifying files, access from outside) after a certain period of time. So we use the cronjob to send requests to the replit (aka access from outside) which does keep the repl online

**Comment by phamleduy04** [comment]
about 404 error, i need to reproduce that

**Comment by phamleduy04** [comment]
<img width="971" alt="Screen Shot 2023-10-17 at 4 21 50 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/f36b6bec-652a-4706-b1c7-3f96942a26e9">

Tried request test with cronjob and its working :)
