### ISSUE TITLE
Replit not generating URL

### ISSUE THREAD

**Issue by Bearmageddon** [phamleduy04/texas-dps-scheduler#75]
Hi!

I'm running the project through Replit and it's working properly according to the console, but the webview is not providing a URL for me to run as a cron job, it simply has a slash. 

Suggestions?

**Comment by lruiabc** [comment]
Please click `new tab` to get the URL. 
<img width="738" alt="Screenshot 2023-11-27 at 11 30 29 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/14931913/1d6d69f6-e126-4ec5-9ddc-5b2cb8f2eca3">

**Comment by phamleduy04** [comment]
Also on your config.yml, make sure `webserver` set to true

**Comment by Bearmageddon** [comment]
webserver was set to true but didn't think about opening a new tab to generate the URL. 

Alternatively, I grabbed it from **Resources** > **Script** > Relevant URL (ends after the first .co - grey box will likely contain your replit username)
![18 32 02](https://github.com/phamleduy04/texas-dps-scheduler/assets/108597680/a3993b3d-e022-4983-bd09-fac8f8f1f869)

Thanks guys.
