### ISSUE TITLE
Only 5 locations in the loop. 

### ISSUE THREAD

**Issue by lruiabc** [phamleduy04/texas-dps-scheduler#77]
HI, 

I have changed the mile to 100, but there is only 5 locations in the loop. Both online and local. 

local: 
<img width="714" alt="Screenshot 2023-11-27 at 11 36 01 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/14931913/1d9e3e68-6b95-4950-9df0-4d87d534313c">

online: 
<img width="1183" alt="Screenshot 2023-11-27 at 11 36 30 PM" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/14931913/dbf60d53-7dde-4e17-b08f-49750ec854df">

**Comment by phamleduy04** [comment]
Duplicate #63. This is DPS API limitation and this is nothing that I can do. The DPS API only returns max 5 locations.
