### ISSUE TITLE
Replit error

### ISSUE THREAD

**Issue by SabbleDabble** [phamleduy04/texas-dps-scheduler#87]
after running for an hour cronjob gives me this error:

 "Failed (HTTP error)
503 Service Unavailable"

**Comment by swaran2** [comment]
Same error. It stopped after running for 3 hours. here are the logs from cron 
<img width="1230" alt="image" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/60092867/3447c2a8-ce51-43a1-9147-8a69d6051607">

**Comment by phamleduy04** [comment]
Does repl.it shows any logs? Can you post that here?

**Comment by Texas1st** [comment]
As a guess, anything 500-related would be on the server end.  TxDPS may be having a website issue.

**Comment by phamleduy04** [comment]
@Texas1st, this 500 status code returned from the running instance so I think this is the program's issue

**Comment by yusufqxzi** [comment]
It's also happening to me. The program automatically stops running when I leave it on for a while, and the cron-job logs will give me http errors

**Comment by phamleduy04** [comment]
I will need to take a look at it. Thank you for bringing it up :)

**Comment by phamleduy04** [comment]
Does anyone have repl.it logs?

**Comment by phamleduy04** [comment]
I can reproduce the error and this might be repl.it problem. I think monitor service trick doesn't keep the repl.it on now.

I will find alternative/workaround and update the video/wiki now.

I would recommend using [Run from your computer](https://github.com/phamleduy04/texas-dps-scheduler/wiki/Installation#run-on-your-computer) or [Docker-compose](https://github.com/phamleduy04/texas-dps-scheduler/wiki/Installation#run-using-docker-compose) if you have docker exprierce.

**Comment by SabbleDabble** [comment]
Yes, I’ve been using an alternative and it worked
Fine!

**Comment by yusufqxzi** [comment]
I wanna run from my computer, but the instructions aren't clear enough and since I don't really program, I'm not familiar with instructions such as "clone the repo" or "install dependencies". What can I do?

**Comment by phamleduy04** [comment]
@SabbleDabble can you share what alternative you are using?

**Comment by phamleduy04** [comment]
@yusufqxzi, 
Make sure u have install node.js (https://nodejs.org/en) (LTS version works)

Clone the repo: download the git as zip (Download zip)
![image](https://github.com/phamleduy04/texas-dps-scheduler/assets/32657584/f5413667-51e7-4b49-a7fd-feb7f13001bd)

After that unzip and Shift + Right click in the unzipped folder and press "Open PowerShell window here".

Install dependencies means type `npm install` on the PowerShell window and enter.

Run the program means type `npm start` on the PowerShell window and enter.
