### ISSUE TITLE
The connection was reset error

### ISSUE THREAD

**Issue by khaiuy2005** [phamleduy04/texas-dps-scheduler#93]
![anh 2](https://github.com/phamleduy04/texas-dps-scheduler/assets/108778983/a13974d0-714b-46f4-bdea-a732e7fc7d72)
I tried to run the code on replit, but as soon as I click run it said the connection was reset. I still put the website URL to cornjob and test run it. It return failed. What should I do 
![anh1](https://github.com/phamleduy04/texas-dps-scheduler/assets/108778983/b6f09a8e-9593-4cec-bd79-98ef8537b9e3)

**Comment by phamleduy04** [comment]
Can you try to use the [GitHub Codespaces](https://github.com/phamleduy04/texas-dps-scheduler/wiki/Installation#github-codespaces) instead Repl.it?
