### ISSUE TITLE
Suggestion - Array of zip codes?

### ISSUE THREAD

**Issue by travelvice** [phamleduy04/texas-dps-scheduler#95]
Since I'm willing to drive much further out than the 5 closest locations it would be nice to be able to drop in various zip codes to expand the pool of possible locations.

Better yet, have some understanding of distance from the starting zip code based on the distance willing to travel criteria and pull those zips in without having to go hunt for zip codes myself.

Cheers for the interesting project.

**Comment by phamleduy04** [comment]
very nice idea, will be on next release ;)

**Comment by phamleduy04** [comment]
The first part (various zip codes) has been implemented in v2.0.0. 

However, this idea:
> Better yet, have some understanding of distance from the starting zip code based on the distance willing to travel criteria and pull those zips in without having to go hunt for zip codes myself.

I'm not sure how it can be done. Any suggestions are very helpful ;). Thanks
